-- MySQL Script generated by MySQL Workbench
-- Thu Feb 20 14:30:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AnalysisEducationalMaterial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AnalysisEducationalMaterial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AnalysisEducationalMaterial` DEFAULT CHARACTER SET utf8 ;
USE `AnalysisEducationalMaterial` ;

-- -----------------------------------------------------
-- Table `AnalysisEducationalMaterial`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnalysisEducationalMaterial`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `emailUser` VARCHAR(100) NULL,
  `loginUser` VARCHAR(45) NULL,
  `passwordUser` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`emailUser` ASC) VISIBLE,
  UNIQUE INDEX `loginUser_UNIQUE` (`loginUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnalysisEducationalMaterial`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnalysisEducationalMaterial`.`Document` (
  `idDocument` INT NOT NULL AUTO_INCREMENT,
  `nameDocument` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idDocument`),
  INDEX `fk_Document_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Document_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AnalysisEducationalMaterial`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnalysisEducationalMaterial`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnalysisEducationalMaterial`.`Theme` (
  `idTheme` INT NOT NULL AUTO_INCREMENT,
  `nameTheme` VARCHAR(100) NULL,
  `Section_idSection` INT NOT NULL,
  `Document_idDocument` INT NOT NULL,
  PRIMARY KEY (`idTheme`),
  INDEX `fk_Theme_Document1_idx` (`Document_idDocument` ASC) VISIBLE,
  CONSTRAINT `fk_Theme_Document1`
    FOREIGN KEY (`Document_idDocument`)
    REFERENCES `AnalysisEducationalMaterial`.`Document` (`idDocument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnalysisEducationalMaterial`.`CleanText`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnalysisEducationalMaterial`.`CleanText` (
  `idCleanText` INT NOT NULL AUTO_INCREMENT,
  `descriptionCleanText` LONGTEXT NULL,
  `Theme_idTheme` INT NOT NULL,
  PRIMARY KEY (`idCleanText`),
  INDEX `fk_CleanText_Theme1_idx` (`Theme_idTheme` ASC) VISIBLE,
  CONSTRAINT `fk_CleanText_Theme1`
    FOREIGN KEY (`Theme_idTheme`)
    REFERENCES `AnalysisEducationalMaterial`.`Theme` (`idTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnalysisEducationalMaterial`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnalysisEducationalMaterial`.`Keyword` (
  `idKeyword` INT NOT NULL AUTO_INCREMENT,
  `descriptionKeyword` VARCHAR(150) NULL,
  `periodicityKeyword` INT NULL,
  PRIMARY KEY (`idKeyword`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnalysisEducationalMaterial`.`RelationCleanText_and_Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AnalysisEducationalMaterial`.`RelationCleanText_and_Keyword` (
  `idRelationCleanText_and_Keyword` INT NOT NULL AUTO_INCREMENT,
  `Keyword_idKeyword` INT NOT NULL,
  `CleanText_idCleanText` INT NOT NULL,
  PRIMARY KEY (`idRelationCleanText_and_Keyword`),
  INDEX `fk_RelationCleanText_and_Keyword_Keyword1_idx` (`Keyword_idKeyword` ASC) VISIBLE,
  INDEX `fk_RelationCleanText_and_Keyword_CleanText1_idx` (`CleanText_idCleanText` ASC) VISIBLE,
  CONSTRAINT `fk_RelationCleanText_and_Keyword_Keyword1`
    FOREIGN KEY (`Keyword_idKeyword`)
    REFERENCES `AnalysisEducationalMaterial`.`Keyword` (`idKeyword`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RelationCleanText_and_Keyword_CleanText1`
    FOREIGN KEY (`CleanText_idCleanText`)
    REFERENCES `AnalysisEducationalMaterial`.`CleanText` (`idCleanText`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
